language: ruby
sudo: false
before_install:
  - gem install bundler -v 1.10
bundler_args: --without development
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - ruby-head
  - 2.3.1
  - 2.2.4
  - 2.1.7
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"
  - "CHECK=commits"

matrix:
  exclude:
    - rvm: ruby-head
      env: "CHECK=rubocop"
    - rvm: 2.3.1
      env: "CHECK=rubocop"
    - rvm: 2.2.4
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
    - rvm: 1.9.3
      env: "CHECK=rubocop"
    - rvm: ruby-head
      env: "CHECK=commits"
    - rvm: 2.3.1
      env: "CHECK=commits"
    - rvm: 2.2.4
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
