language: ruby
sudo: false
bundler_args: --without development extra packaging
before_install:
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1.9|2.0|2.1|2.2) ]]; then
      gem update --system 2.7.8 && gem install bundler -v '< 2' --no-document;
    else
      gem update --system && gem install bundler --no-document;
    fi
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.3.6
  - 2.2.9
  - 2.1.9
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"
  - "CHECK=commits"

matrix:
  exclude:
    - rvm: 2.3.6
      env: "CHECK=rubocop"
    - rvm: 2.2.9
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
    - rvm: 1.9.3
      env: "CHECK=rubocop"
    - rvm: 2.3.6
      env: "CHECK=commits"
    - rvm: 2.2.9
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
