language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  gem update --system --force
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false

matrix:
  include:
    - rvm: 2.5
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.6
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.7
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: jruby-9.2.8.0
      jdk: openjdk8
      env:
        - "_JAVA_OPTIONS='-Xmx1024m -Xms512m'"
        - "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.5
      env: "CHECK=rubocop"

    - rvm: 2.5
      env: "CHECK=commits"

    - rvm: 2.5
      env: "CHECK=warnings"
