language: ruby
sudo: false
bundler_args: --without development
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"
  - "CHECK=commits"

matrix:
  exclude:
    - rvm: 2.2.2
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
    - rvm: 1.9.3
      env: "CHECK=rubocop"
    - rvm: 2.2.2
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
