---
HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vmpooler
    template: redhat-7-x86_64
  pe-aix-71-acceptance:
    roles:
      - agent
    platform: aix-7.1-power
    hypervisor: none
    vmhostname: pe-aix-71-acceptance.delivery.puppetlabs.net
CONFIG:
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
