---
HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
  pe-aix-71-acceptance:
    roles:
      - agent
    platform: aix-7.1-power
    hypervisor: none
    vmhostname: pe-aix-71-acceptance.delivery.puppetlabs.net
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
