HOSTS:
  master:
    roles:
      - master
      - agent
    platform: fedora-20-x86_64
    hypervisor: vcloud
    template: fedora-20-x86_64
  agent:
    roles:
      - agent
    platform: fedora-20-i386
    hypervisor: vcloud
    template: fedora-20-i386
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
