---
HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vmpooler
    template: redhat-7-x86_64
  huawei-ce6850-2-debian-vm-eth0.ops.puppetlabs.net:
    roles:
      - agent
    platform: huaweios-6-powerpc
    hypervisor: none
CONFIG:
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
