HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
    puppetcodedir: /etc/puppetlabs/code
    distmoduledir: /etc/puppetlabs/code/modules
    hieraconf:     /etc/puppetlabs/code/hiera.yaml
    puppetconfdir: /etc/puppetlabs/puppet
    puppetserver-confdir: /etc/puppetserver/conf.d/
    puppetbindir:  /opt/puppetlabs/puppet/bin
    puppetvardir:  /opt/puppetlabs/puppet/cache
    sitemoduledir: /opt/puppetlabs/puppet/modules
  agent:
    roles:
      - agent
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
    puppetcodedir: /etc/puppetlabs/code
    distmoduledir: /etc/puppetlabs/code/modules
    hieraconf:     /etc/puppetlabs/code/hiera.yaml
    puppetconfdir: /etc/puppetlabs/puppet
    puppetbindir:  /opt/puppetlabs/puppet/bin
    puppetvardir:  /opt/puppetlabs/puppet/cache
    sitemoduledir: /opt/puppetlabs/puppet/modules
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
