HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-7-x86_64
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/redhat-7-x86_64
  agent:
    roles:
      - agent
    platform: el-7-x86_64
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/redhat-7-x86_64
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
