HOSTS:
  master:
    roles:
      - master
    platform: el-6-i386
    hypervisor: vcloud
    template: redhat-6-i386
  agent-2003-i386:
    roles:
      - agent
    platform: windows-2003-32
    ruby_arch: x86
    hypervisor: vcloud
    template: win-2003-i386
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
