HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/redhat-6-i386
  agent-2003-x86_64-rubyx64:
    roles:
      - agent
    platform: windows-2003-64
    ruby_arch: x64
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/win-2003-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
