HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/redhat-6-i386
  agent-r2-i386:
    roles:
      - agent
    platform: windows-2003r2-32
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/win-2003r2-i386
  agent-r2-x86_64:
    roles:
      - agent
    platform: windows-2003r2-64
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/win-2003r2-x86_64
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
