HOSTS:
  master:
    roles:
      - master
      - agent
    platform: fedora-18-x86_64
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/fedora-18-x86_64
  agent:
    roles:
      - agent
    platform: fedora-18-i386
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/fedora-18-i386
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
