---
name: Checks

on:
  push:
    branches: [7.x]
  pull_request:
    branches: [7.x]

permissions:
  contents: read

jobs:
  checks:
    name: ${{ matrix.cfg.check }}
    strategy:
      matrix:
        cfg:
          - {check: rubocop, os: ubuntu-latest, ruby: '2.7'}
          - {check: commits, os: ubuntu-latest, ruby: '2.7'}
          - {check: warnings, os: ubuntu-latest, ruby: '2.7'}

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ruby version ${{ matrix.cfg.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.cfg.ruby }}

      - name: Update rubygems and install gems
        run: |
          gem update --system 3.3.26 --silent --no-document
          bundle config set without packaging documentation
          bundle install --jobs 4 --retry 3

      - name: Run ${{ matrix.cfg.check }} check
        run: bundle exec rake ${{ matrix.cfg.check }}
