---
name: Snyk Monitor
on:
  push:
    branches:
      - 7.x
permissions:
  contents: read

jobs:
  snyk_monitor:
    if: ${{ github.repository_owner == 'puppetlabs' }}
    runs-on: ubuntu-latest
    name: Snyk Monitor
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_FOSS_KEY }}
        with:
          command: monitor
          args: --org=puppet-foss --project-name=${{ github.repository }}#${{ steps.extract_branch.outputs.branch }}
